modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License v3.0"
[[mods]]
modId="thalassophobia" 
version="1.0.0"
displayName="Thalassophobia"
# logoFile=""
credits=""
authors="Clebian, Pickle_Face5"
description='''
Adds an ocean dimension and many new ocean themed mobs and items
'''