modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License v3.0"
[[mods]]
modId="thalassophobia" 
version="1.0.0"
displayName="Thalassophobia"
logoFile="logo.png"
credits="Music by DM DOKURO"
authors="Clebian, Pickle_Face5"
description='''
Adds 4 dimensions that represent layers of the ocean
'''
